local_costmap:
  global_frame: odom_combined
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0
